name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minitalk-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minitalk .

      - name: Run tests inside Docker
        run: docker run --rm minitalk | tee minitalk_logs.txt

      - name: Run Valgrind tests
        run: docker run --rm minitalk valgrind --leak-check=full ./client $(docker run --rm minitalk pidof server) "Test Message"

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: minitalk-test-logs
          path: minitalk_logs.txt
