name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

      - name: Build server
        run: make server

      - name: Build client
        run: make client

      - name: Run basic tests
        run: |
          ./server &
          SERVER_PID=$!
          sleep 1
          ./client $SERVER_PID "Hello, Minitalk!"
          sleep 1
          kill $SERVER_PID

      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./server &
          valgrind --leak-check=full --error-exitcode=1 ./client 0 "Hello, Minitalk!"

      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --quiet .

