name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make valgrind cppcheck

      - name: Build all
        run: make all

      - name: Run basic tests
        run: |
          cd exec
          ./server &
          SERVER_PID=$!
          sleep 1
          ./client $SERVER_PID "Hello, Minitalk!"
          sleep 1
          kill $SERVER_PID

      - name: Run Valgrind
        run: |
          cd exec
          valgrind --leak-check=full --error-exitcode=1 ./server &
          SERVER_PID=$!
          sleep 1
          valgrind --leak-check=full --error-exitcode=1 ./client $SERVER_PID "Hello, Minitalk!"
          sleep 1
          kill $SERVER_PID

      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --quiet .

